#pragma once
//C/C++ Includes
#include <iostream>
#include <iomanip>
#include <string>
#include <fstream>
#include <ostream>
#include <vector>
#include <list>
#include <map>

//Dependency Headers
#include "../lib/mdcore-cpp/lib/mdcore/include/mdcore/logger.h"
#include "mdcore/dispatcher.h"
#include "mdcore/command.h"
#include "mdcore/command_listener.h"
#include "mdcore/subcommand_listener.h"
#include "mdcore/utils.h"
#include "sleepy_discord/sleepy_discord.h"
#include "json.hpp"
#include "emoji.h"